name: ToolReplacer Release
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
    branches:
      - main

jobs:
  release_mod:
    runs-on: ["ubuntu-latest"]
    steps:
      - name: "Pull repository"
        uses: actions/checkout@v4

      - name: "Setup java"
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      - name: "Setup gradle"
        uses: gradle/gradle-build-action@v2

      - name: "Execute gradle build"
        run: |
          ./gradlew build