name: ToolReplacer Release
on:
  workflow_dispatch:
    inputs:
      RELEASE_VERSION:
        type: string
        default: "x.x.x"
        description: "Version to release the mod."
        required: true

jobs:
  release_mod:
    runs-on: ["ubuntu-latest"]
    steps:
      - name: "Check parameters"
        run: |
          [[ "${RELEASE_VERSION}" = "x.x.x" ]] && exit 1
        env:
          RELEASE_VERSION: "${{ github.event.inputs.RELEASE_VERSION }}"

      - name: "Pull repository"
        uses: actions/checkout@v4

      - name: "Setup java"
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      - name: "Setup gradle"
        uses: gradle/gradle-build-action@v2

      - name: "Execute gradle build"
        run: |
          ./gradlew -Pmod_version="${RELEASE_VERSION}" build
        env:
          RELEASE_VERSION: "${{ github.event.inputs.RELEASE_VERSION }}"

      - name: "Publish artifact"
        run: |
          ./gradlew -Pmod_version="${RELEASE_VERSION}" publish
        env:
          RELEASE_VERSION: "${{ github.event.inputs.RELEASE_VERSION }}"